=== DevlinV-2261014/Opdracht_ADT/oefening3/root.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="r">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="n" type="xs:int"/>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="a" type="t"/>
                    <xs:element name="b" type="t"/>
                    <xs:element name="c" type="t"/>
                    <xs:element name="d" type="t"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="t">
        <xs:sequence>
            <xs:element name="n" type="xs:int"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="a" type="t"/>
                <xs:element name="b" type="t"/>
                <xs:element name="c" type="t"/>
                <xs:element name="d" type="t"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== DevlinV-2261014/Opdracht_ADT/oefening3/root.xml
<r xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="root.xsd">
    <n>1</n>
    <b>
        <n>5</n>
        <c>
            <n>3</n>
        </c>
        <d>
            <n>4</n>
        </d>
    </b>
    <b>
        <n>6</n>
        <d>
            <n>4</n>
        </d>
        <c>
            <n>3</n>
        </c> <!-- Wrong order, this <b> is ignored -->
    </b>
    <b>
        <n>7</n>
        <c>
            <n>3</n>
        </c>
        <d>
            <n>4</n>
        </d>
    </b>
</r>
